# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker

      - run: 
          name: Build application Docker image
          command: |
            docker build --cache-from=thefreeradicalswebapp -t thefreeradicalswebapp --build-arg port=8080 --build-arg addr=0.0.0.0 .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/thefreeradicalswebapp.tar thefreeradicalswebapp

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/thefreeradicalswebapp.tar

      - deploy:
          name: Push application Docker image
          command: |
            cat /caches/thefreeradicalswebapp.tar | ssh -o "StrictHostKeyChecking no" deploy@incension.com "cat | docker load"
            ssh -o "StrictHostKeyChecking no" deploy@incension.com "docker ps -q --filter ancestor=thefreeradicalswebapp | xargs -r docker stop"
            ssh -o "StrictHostKeyChecking no" deploy@incension.com "docker ps -a -q -f status=exited | xargs -r docker rm -v"
            ssh -o "StrictHostKeyChecking no" deploy@incension.com "docker run -p 8080:8080 -d thefreeradicalswebapp"
